version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=traveldb
      - MYSQL_PASSWORD=12345678
  backend:
    image: backend
    depends_on:
      - db
    links:
      - db
    ports:
      - 8089:8089
  frontend_admin:
    image: frontend_admin
    ports:
      - 8080:8080
  frontend_user:
    image: frontend_user
    ports:
      - 3000:3000
