version: '3.1'
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=traveldb
      - MYSQL_PASSWORD=12345678
  backend:
    image: phanduy0407/backend:v3
    ports:
      - 8089:8089
  frontend_admin:
    image: phanduy0407/frontend_admin:v3
    ports:
      - 8080:8080
  frontend_user:
    image: phanduy0407/frontend_user:v4
    ports:
      - 3000:3000
  recommend:
    image: phanduy0407/recommend:v1
    ports:
      - 8000:8000
